apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
spec:
  # "I need a 1 GB disk that one pod can read and write."
  # Minikube sees this claim and provisions a real disk for it.
  # In Compose this was the 'pgdata' volume; this is its K8s equivalent.
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
